// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/personal_logger.proto

package com.shahramatrian.intuit;

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_intuit_PersonInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_intuit_PersonInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_intuit_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_intuit_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034protos/personal_logger.proto\022\006intuit\032\037" +
      "google/protobuf/timestamp.proto\"\233\001\n\021Pers" +
      "onInfoRequest\022\022\n\nfirst_name\030\001 \001(\t\022\021\n\tlas" +
      "t_name\030\002 \001(\t\022\013\n\003dob\030\003 \001(\t\022\r\n\005email\030\004 \001(\t" +
      "\022\024\n\014phone_number\030\005 \001(\t\022-\n\ttimestamp\030\006 \001(" +
      "\0132\032.google.protobuf.Timestamp\"\033\n\010Respons" +
      "e\022\017\n\007message\030\001 \001(\t2N\n\014PersonLogger\022>\n\017Lo" +
      "gPersonalInfo\022\031.intuit.PersonInfoRequest" +
      "\032\020.intuit.ResponseB*\n\030com.shahramatrian." +
      "intuitB\014PersonProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_intuit_PersonInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_intuit_PersonInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_intuit_PersonInfoRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Dob", "Email", "PhoneNumber", "Timestamp", });
    internal_static_intuit_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_intuit_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_intuit_Response_descriptor,
        new java.lang.String[] { "Message", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
