// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/personal_logger.proto

package com.shahramatrian.intuit;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intuit.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
